# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
