# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160812_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='has_taken',
            field=models.NullBooleanField(),
        ),
    ]
