# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160812_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='has_taken',
            new_name='is_taken',
        ),
    ]
