# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='when_giving',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='when_return',
            field=models.DateField(),
        ),
    ]
