# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160817_1656'),
        ('card', '0002_auto_20160818_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='myuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.MyUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
