# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20160812_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='when_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
