# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20160818_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='users',
        ),
    ]
