# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_card_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='books.Book'),
        ),
    ]
