# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20160812_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='when_giving',
            field=models.DateField(auto_now_add=True),
        ),
    ]
