# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20160812_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='when_giving',
            field=models.DateField(),
        ),
    ]
