# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20160816_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='custom_users',
            new_name='users',
        ),
    ]
